spring.application.name=calculator

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=calculator-module-group
spring.kafka.consumer.auto-offset-reset=earliest

# Kafka Topics (should match REST module)
kafka.topic.request=calculator-requests
kafka.topic.response=calculator-responses

# Logging
logging.level.root=INFO
logging.level.com.wit.calculator=DEBUG

# Calculator Precision
calculator.precision=10
